version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    networks:
      - app-network
    depends_on:
      - postgres

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_DB: voip
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
